# Generated by Django 3.1.7 on 2021-03-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type_of_school', models.CharField(choices=[('kindergarten', 'kindergarten'), ('secondary_school', 'secondary_school'), ('university', 'university')], default='university', max_length=50)),
                ('type_of_edu', models.CharField(choices=[('bachelor', 'bachelor'), ('master', 'master'), ('graduate_sertificate', 'graduate_sertificate')], default='bachelor', max_length=50)),
                ('type_of_univer', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='online', max_length=50)),
                ('name_of_school', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('spec', models.CharField(max_length=50)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.resume')),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
