# Generated by Django 3.1.7 on 2021-03-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_auto_20210324_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='summary.resume'),
            preserve_default=False,
        ),
    ]
